### ISSUE TITLE
Don’t run visualiser on `data/bad`

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#252]
Input in `data/bad` probably cannot be visualised; consider making `bt generate` behave as if `--skip-visualiser` was set for all of `data/bad/*`.

**Comment by thorehusfeldt** [comment]
(Dumb. Seems to occur only if `generators.yaml` has a `data/bad` directory, which doesn’t seem like an intended use case anyway.)

**Comment by RagnarGrootKoerkamp** [comment]
Right, generated `data/bad` testcases would need more hardcoding for edge cases since the generation process also runs validators to ensure anything that's generated passes the tests.

Not sure this is really needed though; just crafting them manually sounds simpler since they should anyway be minimal inputs/outputs that break in some way.
