### ISSUE TITLE
`bt export` skips interactive samples

### ISSUE THREAD

**Issue by mzuenni** [RagnarGrootKoerkamp/BAPCtools#278]
Why are they not exported? We only seem to export `.interaction`, and `.in.statement` for some reason?

**Comment by RagnarGrootKoerkamp** [comment]
I think this has to do with donjudge allowing teams to download sample input and output. But for interactive problems, these are meant to be private. We do usually provide a local test script, but that can use a different format for the `.in`, which should be provided in `/attachements/`. So removing these from the export prevents issues.

Then again, it's nice to run the team submissions on samples, so maybe this should be fixed in domjudge instead.

**Comment by mzuenni** [comment]
hm, maybe they should be added as secret cases? but skipping testcases completely feels wrong ^^'

**Comment by mpsijm** [comment]
Note that we do not _always_ want to run the submissions on the samples. Counterexample: Lowest Latency in BAPC 2022, where we guaranteed that the submission would be run on exactly 100 cases with n = 10⁵, but the sample cases had n = 5 because else it wouldn't fit :stuck_out_tongue: 

In that case, if you explicitly want to include the samples in the secrets folder, probably `include`ing them (#262) would do the trick?

(side-note: the behaviour of `include` doesn't appear to be documented in https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/doc/generators.md or https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/doc/generators.yaml, so I'm not 100% sure if that's how it works, because I didn't really follow the discussion in #262 :innocent:)

**Comment by RagnarGrootKoerkamp** [comment]
For `lowestlatency` we used `data/sample/*.{in,ans}.statement`. So I think this issue is really only for problems with a `data/sample/*.interaction` file, where:
- We don't have `sample/*.in`: nothing is run; OK
- We do have `sample/*.in`, and input is same as for the testing tool: run it and show it, OK.
- We do have `sample/*.in`, but teams shouldn't see it. But we still want to run on it. This is mostly a domjudge issue.

**Comment by mzuenni** [comment]
But how does the case "We do have `sample/*.in`, but teams shouldn't see it." even occur? Shouldn't in that case there be a secret case equal to the sample and the sample be replaced by `.in.statement`?

**Comment by RagnarGrootKoerkamp** [comment]
Well, ideally domjudge would still run on it at show that the submission failed on the sample. We don't usually do that in icpc though.

**Comment by mzuenni** [comment]
In that case i can see why we don't want the file in the `sample.zip` but we still want to judge the testcase?

**Comment by RagnarGrootKoerkamp** [comment]
domjudge has a feature to run on samples and show the output there, or even to not penalize submissions that fail on samples. So for that it's nice to actually have them as samples in the export. But the lazy workaround that we had is to just not make samples for interactive problems.

**Comment by RagnarGrootKoerkamp** [comment]
Well, it's not necessarily that we don't want the internal `.in` files to leak, but more that this turned out to be very confusing for contestants.
