### ISSUE TITLE
Rethink `.gitignore` of `data/`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#305]
**Current situation:**

Setting `gitignore_generated: true` in `generators.yaml` writes `data/.gitignore` when generating, which contains all generated cases, i.e.:
```
.gitignore
secret/1-min.*
secret/2-max.*
bad/empty.*
```

This works nicely, and allows having sample files directly in `data/sample/*`.

**New situation:**

With the new generator spec, having 'inline' source files directly in `data/` is discouraged. It would much simpler and much more consistent to simply ignore all `data` directories in their entirety, and generate warnings for any files in `data/` that are not generated.

A) When to ignore files?
1. Always
2. Only when `gitignore_generated: true` is set

My preference: A1, always, since that's what we always use in practice anyway, and then we can drop the `gitignore_generated` flag and simplify code since there are fewer different usages.

B) Some approaches for ignoring files:
1. Let user put `problems/*/data/` in toplevel `.gitignore` manually.
2. Generate `problem/.gitignore` containing `data/`
3. Generate `problem/data/.gitignore` containing `*`; using the file we currently also use.

My preference: B3, to have automation, but not mess around with a possible `problem/.gitignore` file that could already exist. We can claim ownership of `problem/data/.gitignore` without issues IMO.

C) Some approaches for warning about non-generated files:
1. Always
2. When `gitignore_generate: true` is set
3. When `problem/data/.gitignore` contains `*`, or some specific BAPCtools-generated string/comment.

My preference: C1, again to simplify the implementation and possible use cases.

**Comment by thorehusfeldt** [comment]
B1.

**Comment by mzuenni** [comment]
B3. we want to claim ownership of the whole data dir anyway?

**Comment by RagnarGrootKoerkamp** [comment]
(although not completely independent I think A, Band C each need their own answer ;)

**Comment by mpsijm** [comment]
My preferences are the same as Ragnar and mzuenni: A1, B3, C1 :slightly_smiling_face:

**Comment by RagnarGrootKoerkamp** [comment]
One things that we may want to decide on separately is whether to gitignore samples. It's kinda convenient to have them committed when building PDFs, so they don't have to be re-generated each time `bt pdf` is run somewhere.

**Comment by RagnarGrootKoerkamp** [comment]
Ok so my thinking changed a bit here. I now prefer B1, that users put `*/data/secret` in their toplevel `.gitignore`. That is more explicit than automatically generating `data/.gitignore` files that ignore themselves and hence never show up in `git status` in the first place and are 'completely hidden' to the user.

This makes A void:
- we can drop the `gititnore_generated: true` from `generators.yaml`
- we can drop the code that generates these `.gitignore` files :)
- the user explicitly acknowledges that `data/secret` only exists locally, making it clear that nothing there is permanent.

**Comment by mzuenni** [comment]
My current view is:

- When we generate stuff we always want to gitignore those file i.e. A1. and remove the flag
- B2. But if `data/*` or `!data/secret/*` is not in there we add it (you can comment if if you don't want to ignore it)
- C1. we want to own that directory. Always warn and remove (move to /generators/removed/) files that are not generated

**Comment by mpsijm** [comment]
I've set up the repository for the Freshmen Programming Contests with:
- A1 (i.e. removed the `generate_gitignore` flag, which defaults to `False`)
- B: I've added `data/invalid_*` and `data/secret` to `.gitignore` manually now, but it would indeed be nice to automate adding these rules to some `.gitignore`, either during `bt new_contest` (see https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/skel/contest/.gitignore) or by generating a `.gitignore` file in `data/` which excludes everything except the samples (see https://github.com/RagnarGrootKoerkamp/BAPCtools/issues/309#issuecomment-1787268603). I disagree with B2 (adding a `.gitignore` to every problem), because typically, you'd like an entire contest to use the same configuration, right?

Regarding C (warning about non-generated files), I agree with you guys that `data/` should be completely owned by BAPCtools. However, I do not like the idea of moving removed files to `/generators/removed/`, if that means that old/renumbered test cases will end up in there every time you add new test cases halfway in `generators.yaml`...

**Comment by mzuenni** [comment]
regarding B: I think it has to be a problem specific setting since i dont want that behaviour if i dont use generators?

**Comment by mzuenni** [comment]
yeno, we should only do something with a `.gitignore` if the `generators.yaml` exists and it should therefore be on problem level, but i would prefer to do this is in the more transparent way and write it in the `.gitignore` of the problem directory.

**Comment by mpsijm** [comment]
But if we want this to be transparent, I'd rather set ignore-rules at the level of a contest, because checking in `.gitignore` files for all problems with (roughly) the same ignore-rules feels redundant to me :stuck_out_tongue: And even though this means we don't automate setting ignore-rules on the problem level based on the existence of `generators.yaml`, we could still use the existence of this file to decide whether BAPCtools is allowed to overwrite anything in `data/`.

**Comment by mzuenni** [comment]
IMO there are only two options since contest level should not handle this problem specific setting:

1. write a `.gitignore` in `/data` which ignores itself
2. add something to the problem `.gitignore`

And i simply prefer 2. since self ignoring .gitignore files are weird but i can live with that ^^

**Comment by RagnarGrootKoerkamp** [comment]
Fixed by #348.

choices
- A1: we always ignore files
- B2: we add to `problem/.gitignore`
- C: Instead of warning about unknown files, we move anything old/unknown to `/tmp` and `log` this.
