### ISSUE TITLE
Print logs to stderr instead of stdout

### ISSUE THREAD

**Issue by mpsijm** [RagnarGrootKoerkamp/BAPCtools#92]
I was running `bt gitlabci > .gitlab-ci.yml` with an empty `problems.yaml`, and the command produced no output but did exit with code 1. I couldn't figure out what happened until I found that the `.gitlab-ci.yml` file contained `FATAL ERROR: Did not find any problem in problems.yaml.`

My suggestion is to print errors/warnings/logs/etc. to stderr instead of stdout to avoid situations like this. Only results of subcommands (like `bt gitlabci`, `bt sort`, and `bt tmp`) should be printed to stdout.

What do you think?

**Comment by RagnarGrootKoerkamp** [comment]
Hmmm, tough one. I agree that it would be nice to separate 'machine readable' output and 'human readable' output.
I'm not actually sure how other CLI tools do this.

All of the following are 'valid' in some sense, but not all are compatible:
- nonzero return code implies that you can find the error in stderr
- stderr output implies non-zero return code
- stderr output implies unexpected errors (so errors inside bapctools itself)
- stderr contains all 'diagnostics' (i.e. also logs/progress)

Also see [this stackoverflow](https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout): the answers don't really agree.

Note: `rm` and `find` use `stderr` to prompt for confirmation, so using stderr isn't completely uncommon.

I think I'm leaning towards the following, but feel free to suggest otherwise :)
- explicit error/warn/log/verbose calls go to stderr (verbose only happens with -v or -v, so the user is asking for this)
- progressbar should go to stderr
- the output from progressbar.done() could go to stdout, since this is for normal behavior. This is the most tricky one I think; I can definitely live with stderr as well for this one. Tools may be interested in the changes that were made by running bapctools. Although UI isn't guaranteed to be stable in any way so tools should probably not parse this anyway. -> Actually, stderr is probably easier and more consistent for now
-  We should review all `print(..)` statements outside of `util.py` and check that they are indeed actual 'program output' and not progress/diagnostics. If not, they should probably be changed to log/verbose calls, or a new wrapper that just prints to stderr.

**Comment by mpsijm** [comment]
> Also see [this stackoverflow](https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout): the answers don't really agree.

That's exactly why I wanted to discuss this :stuck_out_tongue: 

> I think I'm leaning towards the following

- Agreed :smile:
- Agreed :smile:
- This is a tricky one indeed :stuck_out_tongue: If other tools may be interested in parsing changes made by running BAPCtools, then the list of changes can be printed to stdout, but the "Done" message belongs more to stderr IMO (just like the progress bar).
- Agreed, this will probably take the most work to get everything right. :joy: 

And additionally:

- Output from subprocesses (e.g. when stderr of submissions is printed with `bt run --error`) should probably also be printed to stderr, but the list of submissions (e.g. `Running accepted/maarten.java:    0.114s ACCEPTED    @ secret/random-3`) could be printed to stdout. But mixing stdout and stderr might lead to desynchronization of the two streams in the terminal (i.e. lines printed in the wrong order), especially with the progress bar also being printed as part of the output :thinking:

**Comment by RagnarGrootKoerkamp** [comment]
Agreed that we shouldn't mix them to prevent desynchronization. In general stderr has less buffering which is good for diagnosticd anyway. (Although this isn't usually a problem anyway.)

Let's change to almost everything stderr, apart from the few where we explicitly like stdout (the ones you mentioned, and stats, and possibly a few more). Probably just (a subset of) the current print statements.
